openapi: 3.0.0
info:
  title: Pathfinder API
  description:
    The Pathfinder API collects real-time weather and traffic conditions for 
    Ngamwongwan road, from the University gate to Kasetsart intersection. 
    Weather data is sourced from OpenWeatherMap.
  version: 1.0.0
servers:
  # use 127.0.0.1 here instead of localhost because openapi-to-graphql would
  # try to use IPv6 ::1, which causes an error
  - url: http://127.0.0.1:8080/pathfinder-api/v1
paths:
  /weather:
    get:
      summary: Returns the current weather conditions.
      operationId: controller.get_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'

  /weather/uniqueDate:
    get:
      summary: Returns the all unique Date.
      operationId: controller.get_weather_unique_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherUniqueDate'
          links:
            weatherbydate:
              operationId: controller.get_weather_by_date
              parameters:
                date: $response.body#/Date
            weatherbyaverage:
              operationId: controller.get_average_weather_by_date
              parameters:
                date: $response.body#/Date

  /weather/{date}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
    get:
      summary: return weather conditions from the specified date.
      operationId: controller.get_weather_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'

  /weather/{date}/{hour}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
      - name: hour
        in: path
        required: true
        schema:
          type: integer
          minimum: 0
          maximum: 23
    get:
      summary: return weather conditions for the specified date and hour.
      operationId: controller.get_weather_by_date_hour
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'

  /weather/{begin}/to/{end}:
    parameters:
      - name: begin
        in: path
        required: true
        schema:
          type: string
          format: date-time
      - name: end
        in: path
        required: true
        schema:
          type: string
          format: date-time
    get:
      summary: Return weather conditions from the specified timestamp range.
      operationId: controller.get_weather_between_timestamps
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'

  /weather/average/{date}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
    get:
      summary: Return average weather conditions for the specified date.
      operationId: controller.get_average_weather_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageWeather'

  /weather/average/{date}/{hour}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
      - name: hour
        in: path
        required: true
        schema:
          type: integer
          minimum: 0
          maximum: 23
    get:
      summary: Return average weather conditions for the specified date and hour.
      operationId: controller.get_average_weather_by_date_hour
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageWeather'

  /weather/average/{begin}/to/{end}:
    parameters:
      - name: begin
        in: path
        required: true
        schema:
          type: string
          format: date-time
      - name: end
        in: path
        required: true
        schema:
          type: string
          format: date-time
    get:
      summary: Return average weather conditions from the specified timestamp range.
      operationId: controller.get_average_weather_between_timestamp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageWeather'

  /traffic:
    get:
      summary: Returns the all traffic statistics.
      operationId: controller.get_traffic_all
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Traffic'

  /traffic/devices:
    get:
      summary: Return all devices that are being tracked.
      operationId: controller.get_devices
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'

  /traffic/device/{deviceID}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device.
      operationId: controller.get_traffic_by_device
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/device/{deviceID}/{begin}/{end}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
      - name: begin
        in: path
        required: true
        schema:
          type: string
      - name: end
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device within the specified time interval.
      operationId: controller.get_traffic_by_device_timestamp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/device/{deviceID}/{date}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
      - name: date
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device within the specified date.
      operationId: controller.get_traffic_by_device_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/device/{deviceID}/weather/{wmain}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
      - name: wmain
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device within the specified weather condition.
      operationId: controller.get_traffic_by_device_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/uniqueDate:
    get:
      summary: Returns the all unique dates of traffic statistics.
      operationId: controller.get_traffic_unique_dates
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UniqueDate'
          links:
            uniqueDate:
              operationId: controller.get_traffic_by_date
              parameters:
                date: $response.body#/Date

  /traffic/uniqueDate/{date}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified date.
      operationId: controller.get_traffic_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/{TravelID}:
    parameters:
      - name: TravelID
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns the all traffic statistics for the specified travelID.
      operationId: controller.get_traffic_by_travel_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/uniqueTravelID:
    get:
      summary: Returns the all unique TravelID.
      operationId: controller.get_traffic_unique_travel_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UniqueTravelID'
          links:
            details:
              operationId: controller.get_traffic_details_by_travel_id
              parameters:
                TravelID: $response.body#/TravelID

  /traffic/details:
      get:
        summary: Returns the average acceleration and time spent for every travelID.
        operationId: controller.get_traffic_details
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/DetailsTraffic'

  /traffic/details/{TravelID}:
    parameters:
      - name: TravelID
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns the average acceleration and time spent form the specified travelID.
      operationId: controller.get_traffic_details_by_travel_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailsTraffic'

components:
  schemas:
    Weather:
      type: object
      properties:
        Timestamp:
          type: string
          format: date-time
        wmain:
          type: string
        wdes:
          type: string
        temp:
          type: number
        hum:
          type: number
        pres:
          type: number
        dp:
          type: number
        uvi:
          type: number
        cloud:
          type: number
        vis:
          type: number
    AverageWeather:
      type: object
      properties:
        date:
          type: string
          format: date
        startTime:
          type: string
        endTime:
          type: string
        wmain:
          type: string
        occurrence_percentage:
          type: number
        avg_temp:
          type: number
        avg_hum:
          type: number
        avg_pres:
          type: number
        avg_dp:
          type: number
        avg_uvi:
          type: number
        avg_cloud:
          type: number
        avg_vis:
          type: number
    WeatherUniqueDate:
      type: object
      properties:
        Date:
          type: string
          format: date

    Traffic:
      type: object
      properties:
        Timestamp:
          type: string
        Latitude:
          type: number
        Longitude:
          type: number
        DeviceID:
          type: string
        acceleration:
          type: number
    Device:
      type: object
      properties:
        DeviceID:
          type: string
    UniqueDate:
      type: object
      properties:
        Date:
          type: string
          format: date
    UniqueTravelID:
      type: object
      properties:
        TravelID:
          type: number
    DetailsTraffic:
      type: object
      properties:
        travelID:
          type: number
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        avg_acceleration:
          type: number
        time_spent:
          type: number
