openapi: 3.0.0
info:
  title: Pathfinder API
  description:
    The Pathfinder API collects real-time weather and traffic conditions for 
    Ngamwongwan road, from the University gate to Kasetsart intersection. 
    Weather data is sourced from OpenWeatherMap.
  version: 1.0.0
servers:
  # use 127.0.0.1 here instead of localhost because openapi-to-graphql would
  # try to use IPv6 ::1, which causes an error
  - url: http://127.0.0.1:8080/pathfinder-api/v1
paths:
  /weather:
    get:
      summary: Returns the current weather conditions.
      operationId: controller.get_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'
  /weather/{begin}/to/{end}:
    parameters:
      - name: begin
        in: path
        required: true
        schema:
          type: string
      - name: end
        in: path
        required: true
        schema:
          type: string
    get:
      summary: return weather conditions from the specified timestamp.
      operationId: controller.get_weather_by_timestamp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'
  /weather/{wmain}:
    parameters:
      - name: wmain
        in: path
        required: true
        schema:
          type: string
    get:
      summary: return time interval and all weather details from the specified weather condition.
      operationId: controller.get_all_by_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'

  /traffic:
    get:
      summary: Returns the all traffic statistics.
      operationId: controller.get_traffic
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Traffic'

  /traffic/devices:
    get:
      summary: Return all devices that are being tracked.
      operationId: controller.get_traffic_all
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'

  /traffic/device/{deviceID}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device.
      operationId: controller.get_traffic_by_device
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/device/{deviceID}/{begin}/{end}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
      - name: begin
        in: path
        required: true
        schema:
          type: string
      - name: end
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device within the specified time interval.
      operationId: controller.get_traffic_by_device_timestamp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/device/{deviceID}/{date}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
      - name: date
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device within the specified date.
      operationId: controller.get_traffic_by_device_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'
  /traffic/device/{deviceID}/{wmain}:
    parameters:
      - name: deviceID
        in: path
        required: true
        schema:
          type: string
      - name: wmain
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified device within the specified weather condition.
      operationId: controller.get_traffic_by_device_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'

  /traffic/uniqueDate:
    get:
      summary: Returns the all unique dates of traffic statistics.
      operationId: controller.get_traffic_unique_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UniqueDate'
          links:
            uniqueDate:
              operationId: controller.get_traffic_by_date
              parameters:
                date: $response.body#/Date

  /traffic/uniqueDate/{date}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns the all traffic statistics for the specified date.
      operationId: controller.get_traffic_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'


components:
  schemas:
    Traffic:
      type: object
      properties:
        Latitude:
          type: number
        Longitude:
          type: number
        Timestamp:
          type: string
        DeviceID:
          type: string
        acceleration:
          type: number
    Device:
      type: object
      properties:
        DeviceID:
          type: string
    UniqueDate:
      type: object
      properties:
        Date:
          type: string
          format: date
