openapi: 3.0.0
info:
  title: Pathfinder API
  description:
    The Pathfinder API collects real-time weather and traffic conditions for 
    Ngamwongwan road, from the University gate to Kasetsart intersection. 
    Weather data is sourced from OpenWeatherMap.
  version: 1.0.0
servers:
  # use 127.0.0.1 here instead of localhost because openapi-to-graphql would
  # try to use IPv6 ::1, which causes an error
  - url: http://127.0.0.1:8080/pathfinder-api/v1
paths:
  /weather:
    get:
      summary: Returns the current weather conditions.
      operationId: controller.get_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/API_weather'
  /weather/{date}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
    get:
      summary: return weather conditions from the specified date.
      operationId: controller.get_weather_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/API_weather'
  /weather/{date}/{hour}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
      - name: hour
        in: path
        required: true
        schema:
          type: integer
          minimum: 0
          maximum: 23
    get:
      summary: return weather conditions for the specified date and hour.
      operationId: controller.get_weather_by_date_hour
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/API_weather'
  /weather/{begin}/to/{end}:
    parameters:
      - name: begin
        in: path
        required: true
        schema:
          type: string
          format: date-time
      - name: end
        in: path
        required: true
        schema:
          type: string
          format: date-time
    get:
      summary: Return weather conditions from the specified timestamp range.
      operationId: controller.get_weather_between_timestamps
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/API_weather'
  /weather/average/{date}:
    parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
    get:
      summary: Return average weather conditions for the specified date.
      operationId: controller.get_average_weather_by_date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    avg_temp:
                      type: number
                    avg_hum:
                      type: number
                    avg_pres:
                      type: number
                    avg_dp:
                      type: number
                    avg_uvi:
                      type: number
                    avg_cloud:
                      type: number
                    avg_vis:
                      type: number
                    wmain:
                      type: string
                    occurrence_percentage:
                      type: number

  /traffic:
    get:
      summary: Returns the current traffic conditions.
      operationId: controller.get_traffic
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Traffic'

  /traffic/{deviceID}:
    parameters:
    - name: deviceID
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns the current traffic conditions for the specified device.
      operationId: controller.get_traffic_by_device
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Traffic'
  /traffic/{begin}/to/{end}:
    parameters:
    - name: begin
      in: path
      required: true
      schema:
        type : string
    - name: end
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns the traffic conditions between the specified timestamps.
      operationId: controller.get_traffic_by_timestamp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Traffic'



components:
  schemas:
    Traffic:
      type: object
      properties:
        Latitude:
          type: number
        Longitude:
          type: number
        Timestamp:
          type: string
        DeviceID:
          type: string
        acceleration:
          type: number
