openapi: 3.0.0
info:
  title: Chaopraya Rainfalls API
  description:
    This API provides historical rainfall data over upper Chaopraya river basin between 1987
    and 2022.  Raw data provided by Thai Meteorological Department (TMD).
  version: 1.0.0
servers:
  # use 127.0.0.1 here instead of localhost because openapi-to-graphql would
  # try to use IPv6 ::1, which causes an error
  - url: http://127.0.0.1:8080/pathfinder-api/v1
paths:

